[versions]
android-compileSdk = "33"
android-minSdk = "21"
android-targetSdk = "33"

kotlin = "1.8.10"
android-gradle-plugin = "8.0.0"

androidx-compose-bom = "2023.04.00"
androidx-compose-compiler = "1.3.2"

coil = "2.3.0"
renderscript-intrinsics-replacement-toolkit = "0.8-beta"

[libraries]
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
renderscript-intrinsics-replacement-toolkit = { module = "com.github.maximillianleonov:renderscript-intrinsics-replacement-toolkit", version.ref = "renderscript-intrinsics-replacement-toolkit" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
